### ISSUE TITLE
Allow non-standard metadata in header block

### ISSUE THREAD

**Issue by zabe40** [kellnerd/userscript-bundler#2]
Tampermonkey has several non-standard headers, such as `@antifeature`, `@sandbox`, and the one I'm interested in using, [`@connect`](https://www.tampermonkey.net/documentation.php#meta:connect). Currently these are silently dropped during the build step. I would prefer for these headers to be passed through and to appear in the header output. If that isn't possible I think that there should at least be a warning that they are being dropped.

**Comment by kellnerd** [comment]
There is currently an allow-list with type definitions for the userscript metadata to make it more convenient to fill in a TypeScript aware IDE.
While I could allow any metadata key with either a string or an array of strings as value, I think it is more safe to have an explicit list of allowed keys.
Moving away from the allow-list would be a breaking change even, as the userscript builder allows an additional key `features` to be specified which is only used to generate the README.

That said, the original allow-list was composed based on the common standards between Greasemonkey, Tampermonkey and Violentmonkey at that time and and my personal decisons.
So it is definitely a good idea to add a few more headers which are accepted by multiple userscript managers such as `@connect`.

**Comment by kellnerd** [comment]
Should be fixed by https://github.com/kellnerd/userscript-bundler/commit/2f1d6137d06a3e1db2bf05fd05e58b2922422a22.
I have added a few new headers, but not `@antifeature` which seems a bit wild and should have a more complex value type than just string if it is to be supported, so I've skipped that.
Let me know whether this works for your use case and I will tag a new release.

**Comment by zabe40** [comment]
Works like a charm, thanks so much!
