### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by jesus2099** [kellnerd/userscript-bundler#4]
Do you know why this one works on windows: https://github.com/zabe40/musicbrainz-userscripts?tab=readme-ov-file#development
But not this one: https://github.com/ROpdebee/mb-userscripts/pull/779#issuecomment-2242718714
?

**Comment by kellnerd** [comment]
Short answer: ROpdebee's userscripts use their own build process and not the one from this repository 😉

I've also checked again since I was able to build ROpdebee's userscripts on a Windows machine in the past (Windows 10 with either cmd.exe, PowerShell or git bash).
But once I updated my local clone beyond https://github.com/ROpdebee/mb-userscripts/commit/a2e7fc741e2af96601c11322145c52817f31ba84 (which changes the build process), it is indeed no longer working and I get the same error as you.
I vaguely remember having fixed a similar issue for the old `ts-node` build process, so there is probably a similar solution for `tsx` 🤔

**Comment by kellnerd** [comment]
Lol, I just found [the commit](https://github.com/ROpdebee/mb-userscripts/commit/afb202d53c94a973c3c54db8ef431ecb5b2984e8) which I remembered and it helped me to solve the issue.
It is literally the same code change in the same file which is required again :joy:
We had reverted it in https://github.com/ROpdebee/mb-userscripts/pull/147 when we switched from ESM to CJS, but now that we are back to ESM it is needed again.

**Comment by kellnerd** [comment]
I created a PR with the fix: https://github.com/ROpdebee/mb-userscripts/pull/780

**Comment by jesus2099** [comment]
You rule! 😁👍
